# This is going to take place of the Makefile parameters ina rubyier way!
# # At the moment, its just an idea!
fpm_ric: 
  name: fpm-rictest
  version: 0.0.42
  description: |
    Yet another Debian distro made from scratch using a ruby gem
    which I like so much!
  copyright: Copyright 2011-11 A few rights reserved (see LICENSE)
  email: riccardo.carlesso@gmail.com
  author_name: 'Riccardo "Palladius" Carlesso'
  dependencies: [ ruby , cowsay, ldaputils ]
#  gems: [ fpm, test, gems ]
